### PR TITLE
#107 Fix makeReducer to use second argument in case of missing third one

### LINKED ISSUE #107: If third tuple argument is not passed to `makeReducer`, the second should be used instead of throwing.

### PR DESCRIPTION
**Pull request by vwerne**
Closes #107

### CODE REVIEW

File: packages/reducers/src/makeReducer.js [hunk 1]
```diff
@@ -20,9 +19,9 @@ const createTypeEqualsPredicate = type => compose(whereEq({ type }), nthArg(1));
 const mergeReducers = ([typePredicate, reducer, errorReducer]) => {
 	const newReducer = (state, action) => {
 		if (prop('error', action)) {
-			invariant(errorReducer, `You haven't supplied an error reducer for action ${action.type}`);
-
-			return errorReducer(state, action);
+			if (errorReducer) {
```
Comment (wafflepie) [inline packages/reducers/src/makeReducer.js]: prefer `if (prop('error', action) && errorReducer)` to nesting ifs

also, please add an entry to changelog (Changed)

```
(_reducers_): `makeReducer` now uses the default reducer for error actions if the error reducer is missing.
```
